[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "smard-utils"
version = "0.1.0"
# dynamic = ["version"]
description = "Utilities for the Marktstammdatenregister"
readme = "README.md"
requires-python = ">=3.10,<4.0"
license = {text = "BSD License"}
authors = [
    {name = "Eduard Moser", email = "eduard.moser@gmx.de"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "flask",
    "requests",
    "uwsgi>=2.0.31,<3.0.0",
    "flask-cors (>=6.0.2,<7.0.0)",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "black>=24.0.0",
    "ruff>=0.1.0",
    "pre-commit",
]

# [dependency-groups]
# dev = [
#     "black>=24.0.0",
#     "ruff>=0.1.0",
#     "pytest",
#     "pytest-cov",
#     "pre-commit",
# ]

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.ruff]
# Ruff ist die moderne All-in-One-Lösung, die Black + Flake8 ersetzt
line-length = 120
select = ["E", "F", "I"] # E=PEP8, F=Logik(F401), I=Isort
ignore = ["E203"]        # Black-Kompatibilität

[project.urls]
Homepage = "https://github.com/fritzthekid/smard-utils"

[project.scripts]
community = "smard_utils.community:main"
biobatsys = "smard_utils.biobatsys:main"
solbatsys = "smard_utils.solbatsys:main"
senec = "smard_utils.senec_analyes:main"
senec2smardformat = "smard_utils.senec2smard:main"
homebatsys = "smard_utils.homebatsys:main"

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
version = {attr = "smard_utils.__version__"}

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

